"""Added type column to clothing_items

Revision ID: 18f02faf44a4
Revises: 
Create Date: 2025-05-04 22:57:25.515785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f02faf44a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_name', sa.String(length=100), nullable=False),
    sa.Column('privacy', sa.Enum('public', 'private', name='privacy-enum'), nullable=False),
    sa.Column('preview_image', sa.String(length=200), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfits')
    op.drop_table('clothing_items')
    op.drop_table('users')
    # ### end Alembic commands ###
