"""Added type column to clothing_items

Revision ID: 18f02faf44a4
Revises: 
Create Date: 2025-05-04 22:57:25.515785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f02faf44a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
##


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'type')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
