"""Create outfit_items table

Revision ID: 4bda7ff2cae3
Revises: 18f02faf44a4
Create Date: 2025-05-07 17:50:44.544551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bda7ff2cae3'
down_revision = '18f02faf44a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.drop_column('clothing_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clothing_type', sa.VARCHAR(length=50), nullable=True))

    op.drop_table('outfit_items')
    # ### end Alembic commands ###
