"""Add dob & height to users

Revision ID: 55745910eb07
Revises: 84f3a340d8bf
Create Date: 2025-05-15 17:03:44.922721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55745910eb07'
down_revision = '84f3a340d8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
