"""Update Outfit model - removed privacy

Revision ID: 84f3a340d8bf
Revises: a93c8a72e64d
Create Date: 2025-05-14 18:41:22.401225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f3a340d8bf'
down_revision = 'a93c8a72e64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.VARCHAR(length=7), nullable=False))
        batch_op.alter_column('date_created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
