"""Add date_created to Outfit

Revision ID: a93c8a72e64d
Revises: 64740b37096f
Create Date: 2025-05-10 23:59:11.803719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93c8a72e64d'
down_revision = '64740b37096f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
